name: 'Publish to npm'
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Which version number should we use for the release"
        type: 'string'
        required: true
  workflow_call:
    inputs:
      version:
        description: "Which version number should we use for the release"
        type: 'string'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: v${{ inputs.version }} # tag that should be created by the caller workflow
      - name: Setup to npm
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - name: Enable corepack
        run: corepack enable
      - name: Build
        run: |
          yarn install --immutable
      - name: Publish to npm
        run: |
          LATEST=$(npm show unleash-server version)
          TAG=$(node scripts/npm-tag.js $LATEST)
          npm publish --tag ${TAG:-latest}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Publish static assets to S3
        run: |
          aws s3 cp frontend/build s3://${{ secrets.S3_STATIC_BUCKET }}/unleash/v${{ inputs.version }} --recursive
